//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.14 at 10:57:21 AM CET 
//


package com.nexocode.bir.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParametryWyszukiwania complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParametryWyszukiwania"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Krs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Krsy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Nip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Nipy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Regon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Regony14zn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Regony9zn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParametryWyszukiwania", namespace = "http://CIS/BIR/PUBL/2014/07/DataContract", propOrder = {
    "krs",
    "krsy",
    "nip",
    "nipy",
    "regon",
    "regony14Zn",
    "regony9Zn"
})
public class ParametryWyszukiwania {

    @XmlElement(name = "Krs", nillable = true)
    protected String krs;
    @XmlElement(name = "Krsy", nillable = true)
    protected String krsy;
    @XmlElement(name = "Nip", nillable = true)
    protected String nip;
    @XmlElement(name = "Nipy", nillable = true)
    protected String nipy;
    @XmlElement(name = "Regon", nillable = true)
    protected String regon;
    @XmlElement(name = "Regony14zn", nillable = true)
    protected String regony14Zn;
    @XmlElement(name = "Regony9zn", nillable = true)
    protected String regony9Zn;

    /**
     * Gets the value of the krs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKrs() {
        return krs;
    }

    /**
     * Sets the value of the krs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKrs(String value) {
        this.krs = value;
    }

    /**
     * Gets the value of the krsy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKrsy() {
        return krsy;
    }

    /**
     * Sets the value of the krsy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKrsy(String value) {
        this.krsy = value;
    }

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNip() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNip(String value) {
        this.nip = value;
    }

    /**
     * Gets the value of the nipy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNipy() {
        return nipy;
    }

    /**
     * Sets the value of the nipy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNipy(String value) {
        this.nipy = value;
    }

    /**
     * Gets the value of the regon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegon() {
        return regon;
    }

    /**
     * Sets the value of the regon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegon(String value) {
        this.regon = value;
    }

    /**
     * Gets the value of the regony14Zn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegony14Zn() {
        return regony14Zn;
    }

    /**
     * Sets the value of the regony14Zn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegony14Zn(String value) {
        this.regony14Zn = value;
    }

    /**
     * Gets the value of the regony9Zn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegony9Zn() {
        return regony9Zn;
    }

    /**
     * Sets the value of the regony9Zn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegony9Zn(String value) {
        this.regony9Zn = value;
    }

}
