//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.14 at 10:57:21 AM CET 
//


package com.nexocode.bir.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PobierzCaptchaResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pobierzCaptchaResult"
})
@XmlRootElement(name = "PobierzCaptchaResponse", namespace = "http://CIS/BIR/2014/07")
public class PobierzCaptchaResponse {

    @XmlElement(name = "PobierzCaptchaResult", namespace = "http://CIS/BIR/2014/07", nillable = true)
    protected String pobierzCaptchaResult;

    /**
     * Gets the value of the pobierzCaptchaResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPobierzCaptchaResult() {
        return pobierzCaptchaResult;
    }

    /**
     * Sets the value of the pobierzCaptchaResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPobierzCaptchaResult(String value) {
        this.pobierzCaptchaResult = value;
    }

}
